services:
  cert:
    build:
      args:
      - CA_SUBJECT=${CA_SUBJECT-/C=US/ST=Denial/L=Springfield/O=Dis/CN=$DOMAIN}
      - CERT_SUBJECT=${CERT_SUBJECT-/C=US/ST=Denial/L=Springfield/O=Dis/CN=$DOMAIN}
      - CERT_EXTENSIONS=${CERT_EXTENSIONS-subjectAltName=DNS:$DOMAIN,DNS:*.$DOMAIN}
      dockerfile_inline: |
        FROM alpine:3

        ARG CA_SUBJECT=/C=US/ST=Denial/L=Springfield/O=Dis/CN=$DOMAIN
        ARG CERT_SUBJECT=/C=US/ST=Denial/L=Springfield/O=Dis/CN=$DOMAIN
        ARG CERT_EXTENSIONS=subjectAltName=DNS:$DOMAIN,DNS:*.$DOMAIN
        
        RUN apk add --no-cache openssl && \
            mkdir -p /opt/certs
        WORKDIR /opt/certs

        # Generate Local CA
        RUN \
            # Generate CA key 
            openssl genrsa -aes256 -passout pass:pass -out ca.key 4096 && \
            # Generate CA cert 
            openssl req -x509 -new -nodes -key ca.key -utf8 -passin pass:pass -sha256 -days 3650 -out ca.cert -subj "$$CA_SUBJECT" && \
            # Generate Service key
            openssl genrsa -out ssl.cert.key 2048 && \
            # Generate Service CSR
            openssl req -new -key ssl.cert.key -utf8 -out service.csr -subj "$$CERT_SUBJECT" && \
            # Generate Service cert
            openssl x509 -req -in service.csr -CA ca.cert -CAkey ca.key -passin pass:pass -CAcreateserial -out ssl.cert -days 825 -sha256 \
                -extfile <(echo "$$CERT_EXTENSIONS") && \
            # Clean up       
            rm -f ca.key service.csr
        
        VOLUME /cert_storage
        VOLUME /trusted_storage
        CMD ["sh", "-c", " \
          cp -f /opt/certs/ssl.cert.key /opt/certs/ssl.cert /cert_storage; \
          cp -f /opt/certs/ca.cert /trusted_storage; \
        "]
    volumes:
    - cert:/cert_storage
    - authority:/trusted_storage
    profiles:
      - local

  vpn:
    image: tailscale/tailscale:latest
    hostname: ${HOSTNAME:-$COMPOSE_PROJECT_NAME}
    environment:
    - TS_AUTHKEY=${TS_AUTHKEY:?Need to set TS_AUTHKEY}
    - TS_STATE_DIR=/var/lib/tailscale
    - TS_USERSPACE=true
    - TS_OUTBOUND_HTTP_PROXY_LISTEN=0.0.0.0:1055
    volumes:
    - tailscale:/var/lib/tailscale
    devices:
    - /dev/net/tun:/dev/net/tun
    cap_add:
    - net_admin
    - sys_admin
    networks:
    - default
    - service
    ports:
    - ${HOST_IPv4:-127.0.0.1}:80:80
    - ${HOST_IPv4:-127.0.0.1}:443:443
    restart: unless-stopped  

  proxy:
    image: nginx:alpine
    configs:
    - source: nginx_conf
      target: /etc/nginx/nginx.conf
    volumes:
    - cert:/etc/nginx/certs
    - ./sablier.js:/etc/nginx/conf.d/sablier.js
    network_mode: service:vpn
    depends_on:
    - vpn
    environment:
    - NGINX_ENTRYPOINT_QUIET_LOGS=1
    restart: always
  manager:
    image: sablierapp/sablier:1.8.6
    command: 
    - start
    - --provider.name=docker
    - --provider.auto-stop-on-startup=true
    - --server.port=80
    - --logging.level=info
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    environment:
    - NO_COLOR=1
    restart: always
  updates:
    image: containrrr/watchtower
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    command: --include-stopped --interval=3600
    restart: always
  dns:
    image: coredns/coredns
    ports:
    - ${HOST_IPv4:-127.0.0.1}:53:53/udp
    - ${HOST_IPv4:-127.0.0.1}:53:53/tcp
    configs:
    - source: Corefile
      target: /Corefile
    restart: always

  ca_ubuntu:
    image: alpine:3
    entrypoint: ["sh", "-c"]
    command: 
    - |
      cp -f /trusted/ca.cert /usr/local/share/ca-certificates/${DOMAIN:-localhost}.crt
      echo "Certficates are copied, dont' forget to run \`sudo update-ca-certificates\` on host"
    volumes:
    - authority:/trusted
    - /usr/local/share/ca-certificates:/usr/local/share/ca-certificates
    env_file:
    - .env
    profiles:
    - ubuntu
  dns_ubuntu:
    image: alpine:3
    entrypoint: ["sh", "-c"]
    command: 
    - |
      cp -f /etc/resolved.conf /etc/systemd/resolved.conf.d/10-$DOMAIN.conf
      echo "resolved config added, dont' forget to run \`sudo systemctl restart systemd-resolved\` on host"
    env_file:
    - .env
    configs:
    - source: resolved_conf
      target: /etc/resolved.conf
    volumes:
    - /etc/systemd/resolved.conf.d:/etc/systemd/resolved.conf.d
    profiles:
    - ubuntu

networks:
  default:
  service:
    name: ${DOCKER_NETWORK:-service}
    driver: bridge
      
configs:
  nginx_conf:
    content: |
      user  nginx;
      worker_processes  auto;

      load_module modules/ngx_http_js_module.so;

      error_log  /var/log/nginx/error.log notice;
      pid        /var/run/nginx.pid;
      
      events {
        worker_connections  1024;
      }

      http {
        include       /etc/nginx/mime.types;
        default_type  application/octet-stream;

        log_format  main  '$$remote_addr - $$remote_user [$$time_local] $$host "$$request" '
                          '$$status $$body_bytes_sent "$$http_referer" '
                          '"$$http_user_agent" "$$http_x_forwarded_for"';

        access_log  /var/log/nginx/access.log  main;

        sendfile        on;
        #tcp_nopush     on;
        charset         utf-8;

        keepalive_timeout  65;

        js_import conf.d/sablier.js;

        server {
          listen      80 default_server;
          listen      443 ssl default_server;
          listen      [::]:80 default_server;
          listen      [::]:443 ssl default_server;
          server_name  _;

          ssl_certificate /etc/nginx/certs/ssl.cert;
          ssl_certificate_key /etc/nginx/certs/ssl.cert.key;
          # error_log /dev/null emerg;

          default_type text/plain;
          return 418 '¯\\_(ツ)_/¯\n';
        }

        map $$host $$sablierNames {
          "~^(?<subdomain>[^\.]+)\..+$$" $$subdomain;
          default "";
        }

        upstream sablier {
          server 127.0.0.1:80;
        }

        server {
          listen      127.0.0.1:80;
          server_name sablier;
          access_log  /dev/null;

          set $$sablierUrl /sablier;
          set $$sablierSessionDuration 15m;
          set $$sablierNginxInternalRedirect @redirect;

          location /sablier/ {
            internal;
            subrequest_output_buffer_size 32k;
            proxy_method GET;
            proxy_pass http://manager/;
          }

          location @redirect {
            return 302 https://$$host$$request_uri;
          }

          location / {
            set $$sablierBlockingTimeout "";
            if ($$http_user_agent !~* "Chrome|Firefox|Safari|Opera|MSIE|Trident") {
              # block request with timeout
              set $$sablierBlockingTimeout 30s;
            }
            set $$sablierDynamicShowDetails true;
            set $$sablierDynamicRefreshFrequency 5s;
            set $$sablierDynamicName "$$sablierNames service";
            set $$sablierDynamicTheme shuffle;
            js_content sablier.call;
          }          
        }

        server {
          listen      80;
          listen      [::]:80;
          server_name .$DOMAIN;

          return 301 https://$$host$$request_uri;
        }

        server {
          listen      443 ssl;
          listen      [::]:443 ssl;
          server_name *.$DOMAIN;
          
          ssl_certificate /etc/nginx/certs/ssl.cert;
          ssl_certificate_key /etc/nginx/certs/ssl.cert.key;

          location / {
            resolver                127.0.0.11 ipv6=off valid=5s;
            proxy_pass              http://$$sablierNames.${DOCKER_NETWORK:-service};
            proxy_set_header        Host $$host;
            proxy_set_header        Upgrade $$http_upgrade;
            proxy_set_header        Connection "upgrade";
            proxy_set_header        X-Forwarded-For $$proxy_add_x_forwarded_for;
            proxy_set_header        X-Real-IP $$remote_addr;
            proxy_buffering         off;
            proxy_request_buffering off;
            proxy_http_version      1.1;
            client_max_body_size    0;
            error_page 502          @manager;
          }

          location @manager {
            proxy_pass              http://sablier;
            proxy_set_header        Host $$host;
            proxy_request_buffering off;
          }
        }
      }

  Corefile:
    content: |
      . {
        acl {
          block
        }
      }
      $DOMAIN {
        errors
        cancel
        template IN ANY $DOMAIN {
          match "^([^.]+)\.$DOMAIN_REGEX\.$$"
          answer "{{ index .Match 1 }}.$DOMAIN 60 IN CNAME $DOMAIN."
          authority "$DOMAIN. 60 IN SOA $DOMAIN. hostmaster.$DOMAIN. (1 60 60 60 60)"
          fallthrough
        }
        template IN ANY $DOMAIN {
          match "^$DOMAIN_REGEX\.$$"
          answer "$DOMAIN. 60 IN A ${HOST_IPv4:-127.0.0.1}"
          answer "$DOMAIN. 60 IN AAAA ${HOST_IPv6:-::1}"
          authority "$DOMAIN. 60 IN SOA $DOMAIN. hostmaster.$DOMAIN. (1 60 60 60 60)"
        }
      }
  resolved_conf:
    # This is used to configure host system's DNS resolver
    content: |
      [Resolve]
      DNS=${HOST_IPv4:-127.0.0.1}
      Domains=~$DOMAIN

volumes:
  tailscale:
  cert:
    name: ssl_${DOMAIN}
  authority:
